### ISSUE TITLE
Write STL Data for Each Grain

### ISSUE THREAD

**Issue by jonathanhestroffer** [CarlSandstrom/Voxel2Tet#2]
Hi Carl,

I am trying to use Voxel2Tet to get smooth surface mesh for a voxelated microstructure. I run the program and I get a .VTP file. How can I process this to get an STL for each grain?

I realize you may have stopped working on this program for a while so I appreciate any input you have,

Best,
Jonathan

**Comment by CarlSandstrom** [comment]
Hi Jonathan,

No, I have not worked on this project for several years, but if I recall correctly it should be quite easy to implement a function to export each grain in one STL file. I will look into it and if it is not too much work, I will implement such a function.

Have a nice weekend,
Carl

**Comment by CarlSandstrom** [comment]
Hi Jonathan,

I added functionality for exporting phase boundaries. If you run the executable, add the flag  "-exportstlphases". You will get one file for each phase. The filename is the same as given in the "-output" argument with an added number (the number of the phase) and ".stl"

Please let me know if this works for you.
Carl

**Comment by jonathanhestroffer** [comment]
Thank you very much Carl!

I will try this out in the coming days. I do have one more question for you
regarding getting good surface mesh.

Some of the experimental microstructures I have tried using the
Voxel2Tet program for do not finish tetrahedralization or even coarsening.
I have a feeling this is due to the creation of very fine "sliver"-like
mesh elements. Through some experimentation I see that the smoothing
algorithm effects certain voxels more than others depending on its
neighbors. Do you have any recommendations as to how I can pre-process my
microstructure before implementing Voxel2Tet? I was thinking that I
could fill in or remove voxels that had low "self coordination number".
Saying that a voxel must have X amount of voxel neighbors with the same Id.

Below is an example of what I believe might be causing problems.

Best,
Jonathan

[image: image.png]
